### ISSUE TITLE
Create search controller, model, view

### ISSUE THREAD

**Issue by joelramsey** [joelramsey/spyderframe#9]

**Comment by joelramsey** [comment]
![analyze main view](https://cloud.githubusercontent.com/assets/8844352/8469229/4f0d46b8-2034-11e5-9b72-0c0e0021cc26.png)
![results main view](https://cloud.githubusercontent.com/assets/8844352/8469231/54706040-2034-11e5-822b-51f4d2b7596c.png)

**Comment by joelramsey** [comment]
![results json view](https://cloud.githubusercontent.com/assets/8844352/8469279/4d48c6a8-2035-11e5-9a14-d04dd81cf531.png)

**Comment by rizwanreza** [comment]
Looking good :+1:
